apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd
spec:
  description: This project hold frontend
  sourceRepos:
    - https://github.com/suyogkumawat/argocd-demos.git
  destinations:
    - namespace: frontend
      server: https://172.31.16.205:33893

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: frontend-admins
      description: Admin for frontend
      policies:
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow     
