apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suyogkumawat/argocd-demos.git    # Replace it with your forked repo
    targetRevision: main
    path: declarative_approach/online_shop
  destination:
    server: https://172.31.16.205:33893   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
